#!/usr/bin/env python3

import os
import subprocess

os.system("rm -rf .git")

subprocess.run(["gh", "repo", "delete", "noufalkdlr/test", "--confirm"])

subprocess.run(["gh", "repo", "create", "noufalkdlr/test", "--public"])

print("New fresh repository created! Ready for testing.")
